### ISSUE TITLE
Security risk - credentials

### ISSUE THREAD

**Issue by abraverm** [JunqiZhang0/Terraform_demo#1]
I've checked and seems like non of the credentials in the repository are active, however this practice is dangerous as simple human error can endagner our account and other people work. I suggest to change how the credentials in TF files are used, or add tests to the repository\git hooks.

**Comment by JunqiZhang0** [comment]
@abraverm Thanks, will do. But this is supposed to show how the vars and states work and look like, so I will keep them there for this moment
